services:
  vllm-server:
    image: vllm/vllm-openai:v0.8.5
    container_name: vllm-node
    runtime: nvidia
    environment:
      - VLLM_USE_V1=0
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - NVIDIA_VISIBLE_DEVICES=all
      - HF_HUB_OFFLINE=0
      - TRANSFORMERS_OFFLINE=0
      - HF_TOKEN=${HF_TOKEN}
      # - HF_HUB_ENABLE_HF_TRANSFER=1
      - HF_DEBUG=1
      - HF_ENDPOINT=https://hf-mirror.com
      # - HTTP_PROXY=http://nginx:80
      # - HTTPS_PROXY=http://nginx:80
      - NO_PROXY=localhost,127.0.0.1,.local,.abc8888.ru,172.0.0.0/8
      # - VLLM_USE_MODELSCOPE=True
      # Игнорируем прокси для HuggingFace
      - NO_PROXY=huggingface.co,cdn-lfs.huggingface.co,.huggingface.co
      - PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
    ports:
      - "8000:8000"
    volumes:
      - /mnt/hdd_data/volumes/vllm_node/models:/root/.cache/huggingface
      - /mnt/hdd_data/volumes/vllm_node/lora_adapters:/app/lora
    networks:
      vllm_network:
        ipv4_address: ${IP_VLLM}
    command: >
      --model Qwen/Qwen2.5-7B-Instruct-AWQ
      --quantization awq
      --gpu-memory-utilization 0.9
      --enable-prefix-caching
      --max-model-len 4096
      --trust-remote-code
      --disable-log-requests
      --max-seq-len-to-capture 4096
      --chat-template-content-format string
      --disable-log-stats
      --max-num-seqs 16
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped

networks:
  vllm_network:
    name: vllm_network
    driver: bridge
    ipam:
      config:
        - subnet: ${SUBNET_VLLM}
